---

- name: Setup NFS shares
  host: NFS-Host
  vars:
    - coreos_shares: '["mongodb", "nginx"]'
  tasks:
    - name: Create nfs direktories
      file:
          path: "/serv/coreos-nfs-shares/{{ item }}"
          state: "directory"
          mode: 0755
          with_items: "{{ coreos_shares }}"
    - name: "Update jenkins systemd files"
      lineinfile:
          dest: ="/etc/exports.d/coreos-cluster-shares.exports"
          line: ="/srv/coreos-nfs-shares/{{ item }}  {{ clientsaccess }}"
          create: "yes"
          mode: "0644"
          with_items: "{{ coreos_shares }}"
    - name: "refreash exportfs"
      shell: "exportfs -ra"

- name: Download CoreOS images
  hosts: CoreOS-VirtHost
  tasks:
    - name: Download and unarchive a file
      unarchive:
          src: https://stable.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2
          dest: "{{ image_dir }}/coreos_production_qemu_image.img"
          remote_src: "yes"
    - name: Copy image
      command: "qemu-img create -f qcow2 -b {{ image_dir }}/coreos_production_qemu_image.img {{ image_dir }}/{{ item }}.qcow2"
      with_items: "{{ coreos_nodes }}"
    - name: Create cloud config directory
      file:
          path: "{{ image_dir }}/{{ item }}/openstack/latest"
          state: "directory"
      with_items: "{{ coreos_nodes }}"
    - name: Create cloud config
      template:
          src: "/user_data.j2"
          dest: "{{ image_dir }}/{{ item }}/openstack/latest/user_data"
      with_items: "{{ coreos_nodes }}"
    - name: Create virtual mashine
      command: |
            virt-install --connect qemu:///system --import \
                 --name {{ item }} \
                 --ram 1024 \
                 --vcpus 1 \
                 --os-type=linux \
                 --os-variant=virtio26 \
                 --disk path={{ image_dir }}/{{ item }}.qcow2,format=qcow2,bus=virtio \
                 --filesystem  {{ image_dir }}/{{ ansible_host }}/,config-2,type=mount,mode=squash \
                 --network bridge=virbr0,type=bridge \
                 --vnc \
                 --noautoconsole
      with_items: "{{ coreos_nodes }}"


- name: Node configs
  hosts: CoreOS-Node
  tasks:
    - name: Create virtual mashine
      chdir: "/tmp/"
      command: "fleetctl submit ./mongodb.service ./nginx.service"
    - name: Create virtual mashine
      command: "fleetctl start mongodb.service nginx.service"
#    - name: "check inventary"
#      debug:
#        msg: "echo  {{ hostvars[ item ].ansible_host}} {{ hostvars[ item ].inventory_hostname}} "
#      with_items: '{{ hostvars }}'
